### ISSUE TITLE
Requesting snapshot of the database

### ISSUE THREAD

**Issue by thibaultduponchelle** [tonycoz/perl_smokes_web#4]
Hi Tony,

As per advised by the README, I'm opening this issue to ask for an up to date snapshot of the database to test against 😃 

Thank you a lot 🙏🏼

**Comment by tonycoz** [comment]
http://files.develop-help.com/perl.develop-help.com/snapshot/

**Comment by thibaultduponchelle** [comment]
Great thank you 👍🏼
